// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bb_asg_lifecycle_hook/bb_asg_lifecycle_hook.proto

package bb_asg_lifecycle_hook

import (
	aws "github.com/buildbarn/bb-storage/pkg/proto/configuration/cloud/aws"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Global          *global.Configuration     `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	AwsSession      *aws.SessionConfiguration `protobuf:"bytes,2,opt,name=aws_session,json=awsSession,proto3" json:"aws_session,omitempty"`
	SqsUrl          string                    `protobuf:"bytes,3,opt,name=sqs_url,json=sqsUrl,proto3" json:"sqs_url,omitempty"`
	Scheduler       *grpc.ClientConfiguration `protobuf:"bytes,4,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	InstanceIdLabel string                    `protobuf:"bytes,5,opt,name=instance_id_label,json=instanceIdLabel,proto3" json:"instance_id_label,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetAwsSession() *aws.SessionConfiguration {
	if x != nil {
		return x.AwsSession
	}
	return nil
}

func (x *ApplicationConfiguration) GetSqsUrl() string {
	if x != nil {
		return x.SqsUrl
	}
	return ""
}

func (x *ApplicationConfiguration) GetScheduler() *grpc.ClientConfiguration {
	if x != nil {
		return x.Scheduler
	}
	return nil
}

func (x *ApplicationConfiguration) GetInstanceIdLabel() string {
	if x != nil {
		return x.InstanceIdLabel
	}
	return ""
}

var File_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDesc = "" +
	"\n" +
	"Ipkg/proto/configuration/bb_asg_lifecycle_hook/bb_asg_lifecycle_hook.proto\x12-buildbarn.configuration.bb_asg_lifecycle_hook\x1a+pkg/proto/configuration/cloud/aws/aws.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\"\xd1\x02\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12X\n" +
	"\vaws_session\x18\x02 \x01(\v27.buildbarn.configuration.cloud.aws.SessionConfigurationR\n" +
	"awsSession\x12\x17\n" +
	"\asqs_url\x18\x03 \x01(\tR\x06sqsUrl\x12O\n" +
	"\tscheduler\x18\x04 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\tscheduler\x12*\n" +
	"\x11instance_id_label\x18\x05 \x01(\tR\x0finstanceIdLabelBRZPgithub.com/buildbarn/bb-autoscaler/pkg/proto/configuration/bb_asg_lifecycle_hookb\x06proto3"

var (
	file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDesc), len(file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDescData
}

var file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil), // 0: buildbarn.configuration.bb_asg_lifecycle_hook.ApplicationConfiguration
	(*global.Configuration)(nil),     // 1: buildbarn.configuration.global.Configuration
	(*aws.SessionConfiguration)(nil), // 2: buildbarn.configuration.cloud.aws.SessionConfiguration
	(*grpc.ClientConfiguration)(nil), // 3: buildbarn.configuration.grpc.ClientConfiguration
}
var file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_asg_lifecycle_hook.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	2, // 1: buildbarn.configuration.bb_asg_lifecycle_hook.ApplicationConfiguration.aws_session:type_name -> buildbarn.configuration.cloud.aws.SessionConfiguration
	3, // 2: buildbarn.configuration.bb_asg_lifecycle_hook.ApplicationConfiguration.scheduler:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_init() }
func file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_init() {
	if File_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDesc), len(file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto = out.File
	file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_goTypes = nil
	file_pkg_proto_configuration_bb_asg_lifecycle_hook_bb_asg_lifecycle_hook_proto_depIdxs = nil
}
