// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bb_autoscaler/bb_autoscaler.proto

package bb_autoscaler

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	aws "github.com/buildbarn/bb-storage/pkg/proto/configuration/cloud/aws"
	http "github.com/buildbarn/bb-storage/pkg/proto/configuration/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	PrometheusHttpClient *http.ClientConfiguration `protobuf:"bytes,5,opt,name=prometheus_http_client,json=prometheusHttpClient,proto3" json:"prometheus_http_client,omitempty"`
	PrometheusEndpoint   string                    `protobuf:"bytes,1,opt,name=prometheus_endpoint,json=prometheusEndpoint,proto3" json:"prometheus_endpoint,omitempty"`
	PrometheusQuery      string                    `protobuf:"bytes,2,opt,name=prometheus_query,json=prometheusQuery,proto3" json:"prometheus_query,omitempty"`
	NodeGroups           []*NodeGroupConfiguration `protobuf:"bytes,3,rep,name=node_groups,json=nodeGroups,proto3" json:"node_groups,omitempty"`
	AwsSession           *aws.SessionConfiguration `protobuf:"bytes,4,opt,name=aws_session,json=awsSession,proto3" json:"aws_session,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetPrometheusHttpClient() *http.ClientConfiguration {
	if x != nil {
		return x.PrometheusHttpClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetPrometheusEndpoint() string {
	if x != nil {
		return x.PrometheusEndpoint
	}
	return ""
}

func (x *ApplicationConfiguration) GetPrometheusQuery() string {
	if x != nil {
		return x.PrometheusQuery
	}
	return ""
}

func (x *ApplicationConfiguration) GetNodeGroups() []*NodeGroupConfiguration {
	if x != nil {
		return x.NodeGroups
	}
	return nil
}

func (x *ApplicationConfiguration) GetAwsSession() *aws.SessionConfiguration {
	if x != nil {
		return x.AwsSession
	}
	return nil
}

type EKSManagedNodeGroupConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	NodeGroupName string                 `protobuf:"bytes,2,opt,name=node_group_name,json=nodeGroupName,proto3" json:"node_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKSManagedNodeGroupConfiguration) Reset() {
	*x = EKSManagedNodeGroupConfiguration{}
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKSManagedNodeGroupConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKSManagedNodeGroupConfiguration) ProtoMessage() {}

func (x *EKSManagedNodeGroupConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKSManagedNodeGroupConfiguration.ProtoReflect.Descriptor instead.
func (*EKSManagedNodeGroupConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescGZIP(), []int{1}
}

func (x *EKSManagedNodeGroupConfiguration) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *EKSManagedNodeGroupConfiguration) GetNodeGroupName() string {
	if x != nil {
		return x.NodeGroupName
	}
	return ""
}

type KubernetesDeploymentConfiguration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinimumReplicas int32                  `protobuf:"varint,3,opt,name=minimum_replicas,json=minimumReplicas,proto3" json:"minimum_replicas,omitempty"`
	MaximumReplicas int32                  `protobuf:"varint,4,opt,name=maximum_replicas,json=maximumReplicas,proto3" json:"maximum_replicas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KubernetesDeploymentConfiguration) Reset() {
	*x = KubernetesDeploymentConfiguration{}
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesDeploymentConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesDeploymentConfiguration) ProtoMessage() {}

func (x *KubernetesDeploymentConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesDeploymentConfiguration.ProtoReflect.Descriptor instead.
func (*KubernetesDeploymentConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesDeploymentConfiguration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesDeploymentConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubernetesDeploymentConfiguration) GetMinimumReplicas() int32 {
	if x != nil {
		return x.MinimumReplicas
	}
	return 0
}

func (x *KubernetesDeploymentConfiguration) GetMaximumReplicas() int32 {
	if x != nil {
		return x.MaximumReplicas
	}
	return 0
}

type NodeGroupConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceNamePrefix string                 `protobuf:"bytes,1,opt,name=instance_name_prefix,json=instanceNamePrefix,proto3" json:"instance_name_prefix,omitempty"`
	Platform           *v2.Platform           `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	SizeClass          uint32                 `protobuf:"varint,6,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*NodeGroupConfiguration_AutoScalingGroupName
	//	*NodeGroupConfiguration_EksManagedNodeGroup
	//	*NodeGroupConfiguration_KubernetesDeployment
	Kind                   isNodeGroupConfiguration_Kind `protobuf_oneof:"kind"`
	WorkersPerCapacityUnit int32                         `protobuf:"varint,4,opt,name=workers_per_capacity_unit,json=workersPerCapacityUnit,proto3" json:"workers_per_capacity_unit,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeGroupConfiguration) Reset() {
	*x = NodeGroupConfiguration{}
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeGroupConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeGroupConfiguration) ProtoMessage() {}

func (x *NodeGroupConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeGroupConfiguration.ProtoReflect.Descriptor instead.
func (*NodeGroupConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescGZIP(), []int{3}
}

func (x *NodeGroupConfiguration) GetInstanceNamePrefix() string {
	if x != nil {
		return x.InstanceNamePrefix
	}
	return ""
}

func (x *NodeGroupConfiguration) GetPlatform() *v2.Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *NodeGroupConfiguration) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

func (x *NodeGroupConfiguration) GetKind() isNodeGroupConfiguration_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *NodeGroupConfiguration) GetAutoScalingGroupName() string {
	if x != nil {
		if x, ok := x.Kind.(*NodeGroupConfiguration_AutoScalingGroupName); ok {
			return x.AutoScalingGroupName
		}
	}
	return ""
}

func (x *NodeGroupConfiguration) GetEksManagedNodeGroup() *EKSManagedNodeGroupConfiguration {
	if x != nil {
		if x, ok := x.Kind.(*NodeGroupConfiguration_EksManagedNodeGroup); ok {
			return x.EksManagedNodeGroup
		}
	}
	return nil
}

func (x *NodeGroupConfiguration) GetKubernetesDeployment() *KubernetesDeploymentConfiguration {
	if x != nil {
		if x, ok := x.Kind.(*NodeGroupConfiguration_KubernetesDeployment); ok {
			return x.KubernetesDeployment
		}
	}
	return nil
}

func (x *NodeGroupConfiguration) GetWorkersPerCapacityUnit() int32 {
	if x != nil {
		return x.WorkersPerCapacityUnit
	}
	return 0
}

type isNodeGroupConfiguration_Kind interface {
	isNodeGroupConfiguration_Kind()
}

type NodeGroupConfiguration_AutoScalingGroupName struct {
	AutoScalingGroupName string `protobuf:"bytes,3,opt,name=auto_scaling_group_name,json=autoScalingGroupName,proto3,oneof"`
}

type NodeGroupConfiguration_EksManagedNodeGroup struct {
	EksManagedNodeGroup *EKSManagedNodeGroupConfiguration `protobuf:"bytes,5,opt,name=eks_managed_node_group,json=eksManagedNodeGroup,proto3,oneof"`
}

type NodeGroupConfiguration_KubernetesDeployment struct {
	KubernetesDeployment *KubernetesDeploymentConfiguration `protobuf:"bytes,7,opt,name=kubernetes_deployment,json=kubernetesDeployment,proto3,oneof"`
}

func (*NodeGroupConfiguration_AutoScalingGroupName) isNodeGroupConfiguration_Kind() {}

func (*NodeGroupConfiguration_EksManagedNodeGroup) isNodeGroupConfiguration_Kind() {}

func (*NodeGroupConfiguration_KubernetesDeployment) isNodeGroupConfiguration_Kind() {}

var File_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDesc = "" +
	"\n" +
	"9pkg/proto/configuration/bb_autoscaler/bb_autoscaler.proto\x12%buildbarn.configuration.bb_autoscaler\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1a+pkg/proto/configuration/cloud/aws/aws.proto\x1a'pkg/proto/configuration/http/http.proto\"\x99\x03\n" +
	"\x18ApplicationConfiguration\x12g\n" +
	"\x16prometheus_http_client\x18\x05 \x01(\v21.buildbarn.configuration.http.ClientConfigurationR\x14prometheusHttpClient\x12/\n" +
	"\x13prometheus_endpoint\x18\x01 \x01(\tR\x12prometheusEndpoint\x12)\n" +
	"\x10prometheus_query\x18\x02 \x01(\tR\x0fprometheusQuery\x12^\n" +
	"\vnode_groups\x18\x03 \x03(\v2=.buildbarn.configuration.bb_autoscaler.NodeGroupConfigurationR\n" +
	"nodeGroups\x12X\n" +
	"\vaws_session\x18\x04 \x01(\v27.buildbarn.configuration.cloud.aws.SessionConfigurationR\n" +
	"awsSession\"m\n" +
	" EKSManagedNodeGroupConfiguration\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12&\n" +
	"\x0fnode_group_name\x18\x02 \x01(\tR\rnodeGroupName\"\xab\x01\n" +
	"!KubernetesDeploymentConfiguration\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10minimum_replicas\x18\x03 \x01(\x05R\x0fminimumReplicas\x12)\n" +
	"\x10maximum_replicas\x18\x04 \x01(\x05R\x0fmaximumReplicas\"\xad\x04\n" +
	"\x16NodeGroupConfiguration\x120\n" +
	"\x14instance_name_prefix\x18\x01 \x01(\tR\x12instanceNamePrefix\x12E\n" +
	"\bplatform\x18\x02 \x01(\v2).build.bazel.remote.execution.v2.PlatformR\bplatform\x12\x1d\n" +
	"\n" +
	"size_class\x18\x06 \x01(\rR\tsizeClass\x127\n" +
	"\x17auto_scaling_group_name\x18\x03 \x01(\tH\x00R\x14autoScalingGroupName\x12~\n" +
	"\x16eks_managed_node_group\x18\x05 \x01(\v2G.buildbarn.configuration.bb_autoscaler.EKSManagedNodeGroupConfigurationH\x00R\x13eksManagedNodeGroup\x12\x7f\n" +
	"\x15kubernetes_deployment\x18\a \x01(\v2H.buildbarn.configuration.bb_autoscaler.KubernetesDeploymentConfigurationH\x00R\x14kubernetesDeployment\x129\n" +
	"\x19workers_per_capacity_unit\x18\x04 \x01(\x05R\x16workersPerCapacityUnitB\x06\n" +
	"\x04kindBJZHgithub.com/buildbarn/bb-autoscaler/pkg/proto/configuration/bb_autoscalerb\x06proto3"

var (
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDesc), len(file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDescData
}

var file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),          // 0: buildbarn.configuration.bb_autoscaler.ApplicationConfiguration
	(*EKSManagedNodeGroupConfiguration)(nil),  // 1: buildbarn.configuration.bb_autoscaler.EKSManagedNodeGroupConfiguration
	(*KubernetesDeploymentConfiguration)(nil), // 2: buildbarn.configuration.bb_autoscaler.KubernetesDeploymentConfiguration
	(*NodeGroupConfiguration)(nil),            // 3: buildbarn.configuration.bb_autoscaler.NodeGroupConfiguration
	(*http.ClientConfiguration)(nil),          // 4: buildbarn.configuration.http.ClientConfiguration
	(*aws.SessionConfiguration)(nil),          // 5: buildbarn.configuration.cloud.aws.SessionConfiguration
	(*v2.Platform)(nil),                       // 6: build.bazel.remote.execution.v2.Platform
}
var file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_depIdxs = []int32{
	4, // 0: buildbarn.configuration.bb_autoscaler.ApplicationConfiguration.prometheus_http_client:type_name -> buildbarn.configuration.http.ClientConfiguration
	3, // 1: buildbarn.configuration.bb_autoscaler.ApplicationConfiguration.node_groups:type_name -> buildbarn.configuration.bb_autoscaler.NodeGroupConfiguration
	5, // 2: buildbarn.configuration.bb_autoscaler.ApplicationConfiguration.aws_session:type_name -> buildbarn.configuration.cloud.aws.SessionConfiguration
	6, // 3: buildbarn.configuration.bb_autoscaler.NodeGroupConfiguration.platform:type_name -> build.bazel.remote.execution.v2.Platform
	1, // 4: buildbarn.configuration.bb_autoscaler.NodeGroupConfiguration.eks_managed_node_group:type_name -> buildbarn.configuration.bb_autoscaler.EKSManagedNodeGroupConfiguration
	2, // 5: buildbarn.configuration.bb_autoscaler.NodeGroupConfiguration.kubernetes_deployment:type_name -> buildbarn.configuration.bb_autoscaler.KubernetesDeploymentConfiguration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_init() }
func file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_init() {
	if File_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto != nil {
		return
	}
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes[3].OneofWrappers = []any{
		(*NodeGroupConfiguration_AutoScalingGroupName)(nil),
		(*NodeGroupConfiguration_EksManagedNodeGroup)(nil),
		(*NodeGroupConfiguration_KubernetesDeployment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDesc), len(file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto = out.File
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_goTypes = nil
	file_pkg_proto_configuration_bb_autoscaler_bb_autoscaler_proto_depIdxs = nil
}
