name: master
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: docker://l.gcr.io/google/bazel:3.3.1
    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Buildifier
      run: bazel run @com_github_bazelbuild_buildtools//:buildifier
    - name: Gazelle
      run: bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro go_dependencies.bzl%go_dependencies -prune && bazel run //:gazelle
    - name: Gofmt
      run: bazel run @go_sdk//:bin/gofmt -- -s -w .
    - name: Clang format
      run: find . -name '*.proto' -exec bazel run @llvm_toolchain//:bin/clang-format -- -i {} +
    - name: Test style conformance
      run: git diff --exit-code HEAD --
    - name: Golint
      run: bazel run @org_golang_x_lint//golint -- -set_exit_status $(pwd)/...
    - name: Check for ineffective assignments
      run: bazel run @com_github_gordonklaus_ineffassign//:ineffassign $(pwd)

    - name: Linux build
      run: bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //...
    - name: Copy bb_autoscaler for Linux
      run: bazel run --run_under cp --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //cmd/bb_autoscaler $(pwd)/bb_autoscaler
    - name: Upload bb_autoscaler for Linux
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_autoscaler.linux_amd64
        path: bb_autoscaler

    - name: macOS build
      run: bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //...
    - name: Copy bb_autoscaler for macOS
      run: bazel run --run_under cp --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //cmd/bb_autoscaler $(pwd)/bb_autoscaler
    - name: Upload bb_autoscaler for macOS
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_autoscaler.darwin_amd64
        path: bb_autoscaler

    - name: FreeBSD build
      run: bazel build --platforms=@io_bazel_rules_go//go/toolchain:freebsd_amd64 //cmd/bb_autoscaler
    - name: Copy bb_autoscaler for FreeBSD
      run: bazel run --run_under cp --platforms=@io_bazel_rules_go//go/toolchain:freebsd_amd64 //cmd/bb_autoscaler $(pwd)/bb_autoscaler
    - name: Upload bb_autoscaler for FreeBSD
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_autoscaler.freebsd_amd64
        path: bb_autoscaler

    - name: Install Docker credentials
      run: mkdir ~/.docker && echo "${DOCKER_CONFIG_JSON}" > ~/.docker/config.json
      env:
        DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON }}
    - name: Push container bb-autoscaler
      run: bazel run //cmd/bb_autoscaler:bb_autoscaler_container_push
